apiVersion: 1

deleteDatasources:
  - name: TaskLattice Prometheus
    orgId: 1

datasources:
  - name: TaskLattice Prometheus
    uid: tasklattice-prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
