observability:
  performanceDebug:
    enabled: true
  tracing:
    otlpEndpoint: http://tempo.monitoring.svc.cluster.local:4318
  profiling:
    serverAddress: http://pyroscope.monitoring.svc.cluster.local:4040
  serviceMonitor:
    labels:
      release: monitoring
  prometheusRule:
    labels:
      release: monitoring
