export const queryKeys = {
  auth: ["identity", "session"] as const,
  users: ["identity", "users"] as const,
  guardrails: ["resources", "guardrails"] as const,
  guardrail: (id: string) => ["resources", "guardrails", id] as const,
  guardrailVersions: (id: string) => ["resources", "guardrail-versions", id] as const,
  controlPacks: ["resources", "control-packs"] as const,
  controls: ["resources", "controls"] as const,
  ruleControls: ["resources", "controls", { implementation: "rules" }] as const,
  controlDefinitions: ["resources", "control-definitions"] as const,
  nativeControls: ["resources", "controls", { implementation: "nemo_native" }] as const,
  nativeControl: (id: string) => ["resources", "controls", { implementation: "nemo_native" }, id] as const,
  actionCatalog: ["resources", "actions"] as const,
  intentAnalysisStatus: ["resources", "intent-analysis-status"] as const,
  playgroundModels: ["resources", "playground-models"] as const,
  playgroundSession: (guardrailId: string) => ["resources", "playground-session", guardrailId] as const,
  testRuns: (guardrailId: string) => ["resources", "test-runs", { guardrailId }] as const,
  allTestRuns: ["resources", "test-runs"] as const,
  testRun: (runId: string) => ["resources", "test-runs", runId] as const,
  testCases: (guardrailId: string) => ["resources", "test-cases", { guardrailId }] as const,
  assignments: ["resources", "assignments"] as const,
  trafficScopeFields: ["resources", "traffic-scope-fields"] as const,
  integrations: ["resources", "integrations"] as const,
  decisions: ["resources", "decisions"] as const,
  metrics: ["resources", "metrics"] as const,
  metricsScope: (filters: { guardrailId?: string; window: string }) => ["resources", "metrics", filters] as const,
  systemStatus: ["resources", "system-status"] as const,
};
