{{- include "tali-guard.validateValues" . }}
{{- if and (not .Values.evaluators.jailbreakDetection.existingSecret) .Values.evaluators.jailbreakDetection.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tali-guard.jailbreakDetectionSecretName" . }}
  labels:
    {{- include "tali-guard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.evaluators.jailbreakDetection.secretKey }}: {{ .Values.evaluators.jailbreakDetection.apiKey | quote }}
{{- end }}
