{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tali-guard.workloadName" . }}
  labels:
    {{- include "tali-guard.workloadLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tali-guard.workloadSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8091
      {{- with .Values.networkPolicy.ingressFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
