apiVersion: v1
kind: Service
metadata:
  name: {{ include "tali-guard.workloadName" . }}
  labels:
    {{- include "tali-guard.workloadLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tali-guard.workloadSelectorLabels" . | nindent 4 }}
